table MarketingData
	lineageTag: f1dfc127-dd82-469b-8f68-41fec9f8e736

	measure TotalGasto =
			SUMX(
			     MarketingData, MarketingData[Gastos_Alimentos] +
			     MarketingData[Gastos_Brinquedos] +
			     MarketingData[Gastos_Eletronicos] +
			     MarketingData[Gastos_Moveis] +
			     MarketingData[Gastos_Utilidades] +
			     MarketingData[Gastos_Vestuario]
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 2f036bda-1cc1-458f-8b07-c87de12e8c1c

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Taxa de Conversão Geral' = ```
			
			VAR TotalCompradores = 
			    CALCULATE(
			        COUNTA(MarketingData[Comprou]), 
			        MarketingData[Comprou] = "Sim"
			    )
			
			VAR TotalPessoasAfetadas = 
			    SUMX(
			        MarketingData, 
			        MarketingData[Campanha1] + 
			        MarketingData[Campanha2] + 
			        MarketingData[Campanha3] + 
			        MarketingData[Campanha4] + 
			        MarketingData[Campanha5]
			    )
			
			RETURN
			    DIVIDE(TotalCompradores, TotalPessoasAfetadas, 0)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 086cf935-5f6a-4534-90b8-22499bff0e41

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 86f5ad24-5c46-4774-aa15-92a356ad5762
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Ano_Nascimento
		dataType: int64
		formatString: 0
		lineageTag: ad97dff5-c7af-4fc5-a3f7-57153a58e0cb
		summarizeBy: sum
		sourceColumn: Ano_Nascimento

		annotation SummarizationSetBy = Automatic

	column Escolaridade
		dataType: string
		lineageTag: dd55cfb4-84b1-4d1d-a062-1bc8e2ca2d70
		summarizeBy: none
		sourceColumn: Escolaridade

		annotation SummarizationSetBy = Automatic

	column Estado_Civil
		dataType: string
		lineageTag: 5fab52f9-90d4-493c-b7d6-ca9f9444d335
		summarizeBy: none
		sourceColumn: Estado_Civil

		annotation SummarizationSetBy = Automatic

	column SalarioAnual
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 6bae17b9-3539-40ab-92a1-074be971dcca
		summarizeBy: sum
		sourceColumn: SalarioAnual

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Filhos_Em_Casa
		dataType: int64
		formatString: 0
		lineageTag: 9f3ceed6-c39b-4498-b0f5-f579834c4203
		summarizeBy: sum
		sourceColumn: Filhos_Em_Casa

		annotation SummarizationSetBy = Automatic

	column Adolescentes_Em_Casa
		dataType: int64
		formatString: 0
		lineageTag: dd3abb37-c930-4394-a202-f9854f8d95e1
		summarizeBy: sum
		sourceColumn: Adolescentes_Em_Casa

		annotation SummarizationSetBy = Automatic

	column Data_Cadastro
		dataType: dateTime
		formatString: Long Date
		lineageTag: 817ed227-b8f8-441b-83de-49f503c90a02
		summarizeBy: none
		sourceColumn: Data_Cadastro

		variation Variation
			isDefault
			relationship: a05345b7-1cc8-44f6-b03e-b430f110bfeb
			defaultHierarchy: LocalDateTable_94ca4567-052b-4c05-9e22-1039c9d99b44.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Recência
		dataType: int64
		formatString: 0
		lineageTag: 503aea6e-9fb6-4c44-ba5a-06391ede26e9
		summarizeBy: sum
		sourceColumn: Recência

		annotation SummarizationSetBy = Automatic

	column Gastos_Eletronicos
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 79925005-483f-4de6-84ba-62e51e124ea4
		summarizeBy: sum
		sourceColumn: Gastos_Eletronicos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Gastos_Brinquedos
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 459b732c-1e29-4cf0-9366-b94667e338bc
		summarizeBy: sum
		sourceColumn: Gastos_Brinquedos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Gastos_Moveis
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ac8bf98c-4f1a-495b-9c01-b287950e4480
		summarizeBy: sum
		sourceColumn: Gastos_Moveis

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Gastos_Utilidades
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d32e81d5-a490-4b59-af32-b244cae9b139
		summarizeBy: sum
		sourceColumn: Gastos_Utilidades

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Gastos_Alimentos
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 017ff3e2-c957-4fa5-b401-6ced4531ed80
		summarizeBy: sum
		sourceColumn: Gastos_Alimentos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Gastos_Vestuario
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: da632a3e-2efa-4787-97e2-89634c7e34f2
		summarizeBy: sum
		sourceColumn: Gastos_Vestuario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Num_Compras_Desconto
		dataType: int64
		formatString: 0
		lineageTag: 26f5ff2a-c549-4c95-93e3-74e9c222ee5f
		summarizeBy: sum
		sourceColumn: Num_Compras_Desconto

		annotation SummarizationSetBy = Automatic

	column Num_Compras_Web
		dataType: int64
		formatString: 0
		lineageTag: 757fe04d-c285-4c93-9850-23a55a580171
		summarizeBy: sum
		sourceColumn: Num_Compras_Web

		annotation SummarizationSetBy = Automatic

	column Num_Compras_Catalogo
		dataType: int64
		formatString: 0
		lineageTag: e3a6bc10-449c-49f1-8cbd-488ac9370018
		summarizeBy: sum
		sourceColumn: Num_Compras_Catalogo

		annotation SummarizationSetBy = Automatic

	column Num_Compras_Loja
		dataType: int64
		formatString: 0
		lineageTag: dc28fc59-fb2f-4df7-8b35-01f68d1d31ae
		summarizeBy: sum
		sourceColumn: Num_Compras_Loja

		annotation SummarizationSetBy = Automatic

	column Num_Visitas_Website_Mes
		dataType: int64
		formatString: 0
		lineageTag: e5bdfe36-27c9-426e-9162-82b50c675323
		summarizeBy: sum
		sourceColumn: Num_Visitas_Website_Mes

		annotation SummarizationSetBy = Automatic

	column Campanha1
		dataType: int64
		formatString: 0
		lineageTag: 9b75eaa5-3248-4c6b-9159-e11f76312ed7
		summarizeBy: sum
		sourceColumn: Campanha1

		annotation SummarizationSetBy = Automatic

	column Campanha2
		dataType: int64
		formatString: 0
		lineageTag: d6e1bb8b-6b3b-4c63-afcf-e881aaf887b0
		summarizeBy: sum
		sourceColumn: Campanha2

		annotation SummarizationSetBy = Automatic

	column Campanha3
		dataType: int64
		formatString: 0
		lineageTag: 19be3370-9c79-486f-a081-74ddad2c78f7
		summarizeBy: sum
		sourceColumn: Campanha3

		annotation SummarizationSetBy = Automatic

	column Campanha4
		dataType: int64
		formatString: 0
		lineageTag: 0a19aa32-f0eb-426a-8f52-458041275f23
		summarizeBy: sum
		sourceColumn: Campanha4

		annotation SummarizationSetBy = Automatic

	column Campanha5
		dataType: int64
		formatString: 0
		lineageTag: 1f5196ff-e3e3-45e8-ad38-94f85f02e880
		summarizeBy: sum
		sourceColumn: Campanha5

		annotation SummarizationSetBy = Automatic

	column Comprou
		dataType: string
		lineageTag: 80623910-b4bb-4afc-9656-1769b8d27b57
		summarizeBy: none
		sourceColumn: Comprou

		annotation SummarizationSetBy = Automatic

	partition MarketingData = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database(),
				    #"project-bbca71a6-cd0b-4b05-99f" = Source{[Name="project-bbca71a6-cd0b-4b05-99f"]}[Data],
				    marketing_campaign1to5_Schema = #"project-bbca71a6-cd0b-4b05-99f"{[Name="marketing_campaign1to5",Kind="Schema"]}[Data],
				    marketingCampaign1to5_Table = marketing_campaign1to5_Schema{[Name="marketingCampaign1to5",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(marketingCampaign1to5_Table,{{"ID", Int64.Type}, {"Salario_Anual", Currency.Type}, {"Gastos_Vestuario", Currency.Type}, {"Gastos_Alimentos", Currency.Type}, {"Gastos_Utilidades", Currency.Type}, {"Gastos_Moveis", Currency.Type}, {"Gastos_Brinquedos", Currency.Type}, {"Gastos_Eletronicos", Currency.Type}, {"Data_Cadastro", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Dias_Desde_Ultima_Compra", "Recência"}, {"Salario_Anual", "SalarioAnual"}}),
				    #"Sorted Rows" = Table.Sort(#"Renamed Columns",{{"SalarioAnual", Order.Ascending}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Sorted Rows",{{"Comprou", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","0","Não",Replacer.ReplaceText,{"Comprou"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","1","Sim",Replacer.ReplaceText,{"Comprou"})
				in
				    #"Replaced Value1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

